2019-07-06 15:29:33,034 ERROR: Exception on /edit_profile [POST] [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/routes.py", line 87, in edit_profile
    if form.validate_on_submit():
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/forms.py", line 41, in validate_username
    user = User.query.filter_by(username=self.username.data).first()
NameError: name 'User' is not defined
2019-07-06 15:30:37,367 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-06 15:30:56,182 ERROR: Exception on /edit_profile [POST] [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/routes.py", line 87, in edit_profile
    if form.validate_on_submit():
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/forms.py", line 41, in validate_username
    user = User.query.filter_by(username=self.username.data).first()
NameError: name 'User' is not defined
2019-07-06 15:31:35,346 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-07 01:52:04,018 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-07 03:25:20,595 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-07 03:25:58,506 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-07 03:32:18,146 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-09 03:40:24,314 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-09 03:41:00,402 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-09 05:19:54,712 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-09 05:21:56,151 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-09 05:22:39,497 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-09 05:24:56,644 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
